### PR TITLE
smol refactor + slash commands

### PR DESCRIPTION
**Pull request by isthistechsupport**

### CODE REVIEW

**Comment by isthistechsupport** [comment]
bot basedness increased from JavaCringe to based snek

**Comment by Anlesvavor** [comment]
Lbtm (I hate snek)

**Comment by gageway1** [comment]
Interesting concept however rewrite it in rust

**Comment by gageway1** [comment]
this still isn't written rust but i suppose it works for now.

**Review by gageway1 — APPROVED** [review]

**Pull request merged**
